#!/usr/bin/env bash
#output some information about a file
file="Bestschool"
if [ -e $file ]; then
    echo $file school file exists
    if [ -s $file ]; then
	echo $file school file is not empty
    else
	echo $file school file is empty
    fi
    if ! [ -d $file ]; then
	echo $file school is a regular file
    fi
else
    echo $file school file does not exist
fi
